#!/bin/bash
#
# github always rebases even for FF so you can't easily delete a branch
# without it complaining about being non merged.
#

arg="$1"
test -z "$arg" && echo "Usage: $(basename "$0") [--all|<branchname>]" && exit 1

delete_branch () {
    branch="$1"

    sha=$(git log -n1 --pretty=format:%H)

    set -e
    git log -n1 --format=short
    git checkout --quiet "$branch"
    set +e
    if ! git -c advice.skippedCherryPicks=false rebase --quiet "$sha"; then
        git rebase --abort
        git checkout -f -
        echo "Failed to rebase, aborting"
        return 1
    fi
    git branch --unset-upstream > /dev/null 2>&1
    git checkout --quiet -
    git branch -d "$branch"
    set -e
}

if [ "$arg" = "--all" ]; then
    for branch in $(git branch | grep wip); do
        delete_branch "$branch"
    done
else
    delete_branch "$arg"
    exit $?
fi
