#!/bin/bash

usage() {
    echo "`basename $0` enable|disable <hook>"
}

if [[ $# < 1 ]]; then
    usage
    exit 1
fi

cmd=$1
hook=$2
hook_disabled=$hook.disabled
case $cmd in
    enable)
        ;;
    disable)
        ;;
    *)
        usage
        exit 1
        ;;
esac

git rev-list HEAD~..HEAD > /dev/null
if [ $? -ne 0 ]; then
    exit 1
fi

# git rev-list will take care of searching for the git-repo
# so if we get here, we know we're inside a git repo.
while ! [ -e ".git" ]; do
    cd ..
done

pushd .git/hooks > /dev/null || exit 1

case $cmd in
    enable)
        if ! [[ -e "$hook_disabled" ]]; then
            echo "Hook $hook_disabled does not exist"
            exit 1
        fi
        mv $hook_disabled $hook
        ;;
    disable)
        if ! [[ -e "$hook" ]]; then
            echo "Hook $hook does not exist"
            exit 1
        fi
        mv $hook $hook_disabled
        ;;
    *)
        ;;
esac

popd > /dev/null || exit 1
