#!/bin/sh

# fake some name that looks like a git commit to vim
if [ $# -ne 1 ]; then
    echo  "usage: $0 <commit range>"
fi

FAKE_GIT_DIR=`mktemp -d`
FILE=$FAKE_GIT_DIR/.git/COMMIT_EDITMSG
mkdir -p $FAKE_GIT_DIR/.git/

$EDITOR $FILE
git filter-branch -f --msg-filter "sed '\$a `cat $FILE`'" $1
rm -rf $FAKE_GIT_DIR
